/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDraggable {
        "dropData": any;
        "droppable": any;
    }
    interface AppDroppable {
        "complete": (ev: any, data: any) => Promise<void>;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppDraggableElement extends Components.AppDraggable, HTMLStencilElement {
    }
    var HTMLAppDraggableElement: {
        prototype: HTMLAppDraggableElement;
        new (): HTMLAppDraggableElement;
    };
    interface HTMLAppDroppableElement extends Components.AppDroppable, HTMLStencilElement {
    }
    var HTMLAppDroppableElement: {
        prototype: HTMLAppDroppableElement;
        new (): HTMLAppDroppableElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-draggable": HTMLAppDraggableElement;
        "app-droppable": HTMLAppDroppableElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppDraggable {
        "dropData"?: any;
        "droppable"?: any;
    }
    interface AppDroppable {
        "onElementDropped"?: (event: CustomEvent<any>) => void;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-draggable": AppDraggable;
        "app-droppable": AppDroppable;
        "app-home": AppHome;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-draggable": LocalJSX.AppDraggable & JSXBase.HTMLAttributes<HTMLAppDraggableElement>;
            "app-droppable": LocalJSX.AppDroppable & JSXBase.HTMLAttributes<HTMLAppDroppableElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
